### ISSUE TITLE
Implement hoodie.reset()

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client#12]
Reset hoodie client and emit `reset` events so plugins can reset as well. Should implement a way so that plugins can hook into the reset with async operations

```js
hoodie.reset().then(function () {
  // clean slate again
})
```

And plugins could do something like

```js
hoodie.on('reset', function (options) {
  options.promise = options.promise.then(function () {
    // do some async reset here
  })
})
```

^^ This is just a suggestion, maybe there are better patterns for it :)

- [ ] Update README as part of PR

**Comment by danreeves** [comment]
Hi :wave: 

I'm gunna try to make a PR for this tonight. Sound good?

**Comment by gr2m** [comment]
Sounds amazing :) All yours

**Comment by gr2m** [comment]
Hey @danreeves what’s status?

**Comment by danreeves** [comment]
Hi @gr2m, finally had some time to look at this tonight. I've had some issues getting hoodie@next and hoodie-client working together but that's maybe another issue. I've made a WIP PR here: https://github.com/hoodiehq/hoodie-client/pull/32

Looking like the right direction?

**Comment by gr2m** [comment]
Awesome I'll check it out tomorrow, thanks a ton!

**Comment by Guria** [comment]
@gr2m I am not guru in api design, but `options.promise = options.promise.then` looks ugly for me. can't we just return promise and manage it from callback caller instead?

**Comment by gr2m** [comment]
Yeah I’m wondering if there is a nicer API :) But the one with `options.promise` is  the best shot right now, as we can’t get the value that is returned by event handlers

```js
hoodie.on('reset', function () {
  return new Promise(...) // this goes nowhere
})

hoodie.trigger('reset')
```

**Comment by gr2m** [comment]
@Guria here’s an alternative API suggestion to intercept things like `reset` events: https://github.com/hoodiehq/hoodie-client/issues/42

**Comment by danreeves** [comment]
@gr2m looks similar to something I was working on to get the .reset() call to be thenable without racing the event listeners: https://github.com/danreeves/hoodie-client/commit/9ded20e918165c37b3b1f00ce04faa5c33248137

**Comment by gr2m** [comment]
@danreeves clever!!

**Comment by gr2m** [comment]
@danreeves let’s put `hoodie.reset` on hold for now. We have to think about the hooks as we need it for the glue code between `hoodie.store` and `hoodie.account`, but `hoodie.reset` only becomes relevant with plugins which we put out of scope for the first release. I like your `options.hooks` idea, maybe we can use that implementation for the hooks in sign in / sign out

**Comment by danreeves** [comment]
Yeah, that makes sense
