### ISSUE TITLE
💯 test coverage

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client#129]
I don’t know when and why exactly, but we dropped our 100% test coverage.

I’ve reduced coverall’s required coverage to 97% for the time being. Once fixed, we have to get it back to 100%. Setting is at https://coveralls.io/github/hoodiehq/hoodie-client/settings

See https://github.com/hoodiehq/hoodie-client/issues/79 for instructions how to run coverage locally

**Comment by sohini-roy** [comment]
I would love to work on this issue :)
