### ISSUE TITLE
Implement hoodie.on / hoodie.one / hoodie.off / hoodie.trigger methods

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client#14]
You can see pouchdb-hoodie-api is doing it: https://github.com/hoodiehq/pouchdb-hoodie-api/blob/master/index.js#L25-L27

- [ ] update [README.md](https://github.com/hoodiehq/hoodie-client/blob/master/README.md) as part of the PR

**Comment by byronhulcher** [comment]
I'm investigating this as a part of the NYC hoodie event!

**Comment by byronhulcher** [comment]
Fixed by https://github.com/hoodiehq/hoodie-client/pull/17
