### ISSUE TITLE
Arguments ignored in custom events

### ISSUE THREAD

**Issue by gnowoel** [hoodiehq/hoodie-client#156]
From the [docs](http://docs.hood.ie/en/latest/api/client/hoodie.html#hoodie-trigger), the signature of the `hoodie.trigger()` method is:

```js
hoodie.trigger(eventName[, option1, option2, ...])
```

However, the optional arguments are simply ignored in the [implementation](https://github.com/hoodiehq/hoodie-client/blob/7eb0da2a3eb5af7e113b3dd4acc639cafdebbdcb/lib/events.js#L54):

```js
state.emitter.emit(eventName)
```

In effect, when we trigger a custom event with:

```js
hoodie.trigger('name', object);
```

The passed-in `object` will always be `undefined` in the event handler:

```js
hoodie.on('name', (object) => {
  console.log(object); //=> undefined
});
```

**Comment by gr2m** [comment]
You are right 👍 That’s a proper bug. Would you mind sending a pull request to fix it? Happy to assist if you have any questions

**Comment by gnowoel** [comment]
Sure, would be glad to help :)
