### ISSUE TITLE
Project still alive?

### ISSUE THREAD

**Issue by DominikGuzei** [hoodiehq/hoodie-client#170]
I have heard about Hoodie a few years ago and stumbled over it today while looking for client side data storage / syncing solutions. I like the concept but it seems like the activity around this project has gone really quiet in the last year?

**Comment by gr2m** [comment]
It’s still in use, but not many contributions right now, which doesn’t mean that it’s not active. I’d rather not ask such question in general in volunteer run communities

**Comment by DominikGuzei** [comment]
Sorry @gr2m, didn't want to offend anyone … it's just important to know how much momentum is still behind the project. I saw many missing parts in the docs last commits often one year ago, so i thought i'd ask directly in case i overlooked something (e.g: a shift to another project etc.)

I could also ask the same question in general about couchDB as it seems like it hasn't really taken off compared to other solutions (with that i mean the community / backing seems to be quite small).

**Comment by gr2m** [comment]
last release from CouchDB is form August, seems to be doing well for me? And it’s widely used, just doesn't have VC-backed marketing like others ;)

**Comment by DominikGuzei** [comment]
After a bit more research i found several high-profile alternatives that cover much more ground to make writing (mostly) serverless apps a breeze :)

Examples:
https://realm.io/
https://firebase.google.com/

**Comment by gr2m** [comment]
if you look for serverless, Hoodie is not a good solution for ya anyway ;)
