### ISSUE TITLE
Implement hoodie.plugin

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client#2]
`hoodie.plugin` takes a function which receives `hoodie` as its first argument.

### Example

```js
hoodie.plugin(function(hoodie) {
  hoodie.sayHi = function() {
    alert('say hi!');
  };
});

hoodie.sayHi(); // shows alert
```

---

- [x] Implement tests in `tests/specs/plugin`, require it in `tests/index.js`
- [x] Make sure tests fail when you run `npm test`
- [x] Implement the method in `lib/plugin.js` until tests are green
- [x] update README.md
- [x] send a PR
- [ ] review & merge

**Comment by boennemann** [comment]
I just came across this issue and I don't get the API design. What is the difference between the hoodie object `.plugin` is called on and the one that is passed into the function? If there is a difference: Why? And how is that not confusing?

If there is no difference what does this API offers us as a benefit? How can validate things or get control over the way people modify the hoodie object, and what is the difference to removing the entire wrapper?

```
hoodie.sayHi = function() {
  alert('say hi!');
};

hoodie.sayHi(); // shows alert
```

I'd prefer PouchDB's API here: http://pouchdb.com/api.html#plugins

**Comment by gr2m** [comment]
The difference is I can put my plugin into a node module

```js
module.exports = function(hoodie) {
  hoodie.sayHi = function() {
    alert('say hi!');
  };
}
```

**Comment by christophwitzko** [comment]
That makes sense, but why is the `plugin` function necessary for that?
You can simply require that module:
```javascript
require('./mymodule.js')(hoodie)
hoodie.sayHi() // shows alert
```

**Comment by gr2m** [comment]
I think the idea was, that the plugin function takes both, and object and a function. If you pass an object, it works like PouchDB’s `.plugin` method. And if you pass the function, you get the Hoodie context and can go nuts at your own risk, similar to what jQuery does

**Comment by christophwitzko** [comment]
Sounds good to me! :relaxed: :+1:

**Comment by gr2m** [comment]
I agree that technically, we don't need a plugin method. But I think it makes simpler to explain how to extend the `hoodie` client API if there is a dedicated method for it, with its own documentation, where we can send people to

**Comment by nathanstilwell** [comment]
Why don't we do both? So,

**sayHi.js**
```js
module.exports = function(hoodie) {
  hoodie.sayHi = function() {
    alert('say hi!');
  };
}
```

**Example**
```js
const sayHi = require('sayHi');

hoodie.plugin(sayHi);

// or 

hoodie.plugin({
  sayHi: sayHi,
  someOtherPlugin: otherPlugin
})
```

**Comment by nathanstilwell** [comment]
Ha ha, nevermind. I just wrote the test and I don't think it's going to work. Because,

```js
const sayHi = require('sayHi')
const otherPlugin = require('otherPlugin')

// or 

hoodie.plugin({
  sayHi: sayHi,
  someOtherPlugin: otherPlugin
})
```

in this example, `otherPlugin` isn't going to be `hoodie.otherPlugin`, it's going to be `hoodie.someOtherPlugin`. I'm pretty sure I could get this working, but that seems confusing.

But, one thing I do like from the [Pouch plugin docs](http://pouchdb.com/api.html#plugins) is chaining plugin calls.

```js
hoodie
  .plugin(sayHi
  .plugin(otherPlugin)
```

**Comment by gr2m** [comment]
released as https://github.com/hoodiehq/hoodie-client/releases/tag/v2.4.0
