### ISSUE TITLE
Bring code coverage to 100%

### ISSUE THREAD

**Issue by toh82** [hoodiehq/hoodie-client#46]
current status: [![Coverage Status](https://coveralls.io/repos/github/hoodiehq/hoodie-client/badge.svg?branch=master)](https://coveralls.io/github/hoodiehq/hoodie-client?branch=master)
```
npm run test:coverage

...
=============================== Coverage summary ===============================
Statements   : 85.57% ( 83/97 )
Branches     : 93.1% ( 27/29 )
Functions    : 58.82% ( 10/17 )
Lines        : 85.57% ( 83/97 )
================================================================================

```

---
- [x] claim this issue (@janpawellek)
- [x] start a pull request (#64) 
- [x] write tests until 100% coverage is reached
- [ ] review & merge

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq) if you have ​​_any_​​ questions

**Comment by janpawellek** [comment]
I'm clueless how to cover these lines in index.js:
![screenshot from 2016-03-02 16 38 18](https://cloud.githubusercontent.com/assets/2392542/13465307/667eb35a-e095-11e5-9a79-667cf6df67a8.png)

options.ajax gets deleted in hoodie-client-store and I see no way of accessing it. Could anybody help?

Thank you!
Jan

**Comment by gr2m** [comment]
okay the `hoodie-client` is a bit of a mess still, we are still figuring things out how to combine all the other hoodie frontend libraries.

Here is an idea to make it easier to test. Move all the code that assembles `api` into an internal method, so that the constructor in the end would look like this:

```js
function Hoodie (options) {
  var state = getState(options)
  var api = getApi(state)
  init(api)
  return api
}
```

In `lib/get-api.js` you would require the other libs like this:

```js
var internals = {}
internals.Store = require('hoodie-client-store')
internals.Account = require('hoodie-client-account')
internals.ConnectionStatus = require('hoodie-client-connection-status')
internals.Log = require('hoodie-client-log')
module.exports.internals = internals
```

Then you can use [simple-mock](https://www.npmjs.com/package/simple-mock) to mock these libraries in your tests, e.g. 

```js
var simple = require('simple-mock')
// ...
var CumstStoreMock = simple.stub()
simple.mock(internals, 'Store', {
  defaults: function () {
    return CumstStoreMock
  }
})
var state = { /* simulate state here */ }
var api = getApi(state)
var storeAjaxParam = CumstStoreMock.lastCall.args[1]
t.is(storeAjaxParam().headers.authorization, 'Bearer sessionId123')
```

**Comment by janpawellek** [comment]
Thank you @gr2m this was really helpful! Now the PR is ready :smile:

**Comment by gr2m** [comment]
Hey @janpawellek, the coverage fell below 100% again after we fixed several things, we (well, I) missed to add new tests, too. Just in case you’re up for it, feel free to assign yourself: https://github.com/hoodiehq/hoodie-client/issues/79
