### ISSUE TITLE
does not sync on pageload

### ISSUE THREAD

**Issue by PatrickKubica** [hoodiehq/hoodie-client#48]
Hi,

While using the something tracker app I noticed that when adding a new tracked item the new item will not show up in the couch db user table.
Only when I call hoodie.store.connect() in the console the sync is working correctly.
The same thing happens when entering a new value in the database.
It will not automatically sync and the sync needs to be triggered manually.

**Comment by gr2m** [comment]
For context: in the current hoodie stable version, we validate the current session, then call connect: https://github.com/hoodiehq/hoodie/blob/hoodie-client-legacy/src/hoodie.js#L69

In the new hoodie, I’d check if use is signed in. If they are, call `hoodie.store.connect()` immediately.

**Comment by gr2m** [comment]
closing in favor of #54
