### ISSUE TITLE
[hoodie.store] Validate storage value

### ISSUE THREAD

**Issue by janl** [hoodiehq/hoodie-client#5]
![screen shot 2015-10-01 at 10 38 40](https://cloud.githubusercontent.com/assets/11321/10216343/9af05386-6828-11e5-9ae8-b751d8f0eb53.png)

e.g. we should send a helpful error message if someone tries to store a string, int, bool or array (or any non-`Object`)

**Comment by gr2m** [comment]
the new hoodie.store now throws an error if you pass in something invalid

```js
var Store = require("hoodie-client-store")
var store = new Store('test', {remote: 'http://example.com', db : require('memdown')})
store.add(123)
.catch(console.log)
// PouchError: Document must be a JSON object
```

You can try that on https://tonicdev.com/npm/hoodie-client-store
