### ISSUE TITLE
README: setup instructions

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client#68]
![welcome-to-open-source-atlanta](https://cloud.githubusercontent.com/assets/39992/13732817/58766428-e960-11e5-8496-c65891ad0835.png)

**This issue is reserved for participants of [Welcome to Open Source, Atlanta](http://www.meetup.com/Jr-Dev-Mentoring/events/228951389/)**.
If it’s still available after April 2nd, it’s all yours :)

---

### :bug: The Bug

In the [testing section of this repository’s README](https://github.com/hoodiehq/hoodie-client#testing) we tell the user to clone the repository using `git clone git@github.com:hoodiehq/hoodie-client.git`. But GitHub itself recommends the `https://` protocol instead of the `git@` which is SSH (see [which remote should I use](https://help.github.com/articles/which-remote-url-should-i-use/)).

### :dart: The Goal

Replace the `git clone git@github.com:hoodiehq/hoodie-client.git` with `https://github.com/hoodiehq/hoodie-client.git` in the README

### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request

- [ ] claim this issue (comment below)
- [ ] Clone the repository to your computer
- [ ] Edit the `README.md` file.
- [ ] Commit the change `docs(README): fixed git clone URL`
- [ ] Start a Pull Request.  Mention `closes #68` in the description of the pull request
- [ ] Done :+1: Comment below to ask for a review :)

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/) if you have any questions :)

**Comment by HopeMobile** [comment]
claiming this

**Comment by hintsa** [comment]
.

**Comment by hintsa** [comment]
claim this here

**Comment by gr2m** [comment]
@hintsa sorry it’s already done in #69 :)
