### ISSUE TITLE
Bring code coverage to 100% (again)

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client#79]
Since https://github.com/hoodiehq/hoodie-client/issues/46 we had some refactoring and bugfixing, and the code coverage fell down to 91% (that was me, I’m sorry :( )

current status: [![Coverage Status](https://coveralls.io/repos/hoodiehq/hoodie-client/badge.svg?branch=master)](https://coveralls.io/r/hoodiehq/hoodie-client?branch=master)

```
$ npm run test:coverage

=============================== Coverage summary ===============================
Statements   : 91.61% ( 131/143 )
Branches     : 87.18% ( 34/39 )
Functions    : 84.38% ( 27/32 )
Lines        : 91.61% ( 131/143 )
================================================================================
```

After you run `npm run test:coverage` you can open `coverage/lcov-report/index.html` in your browser, it will show a lot of details on which parts of the code is not yet covered. There are a few lines not covered in client/lib/init.js, here’s a preview

<img width="1618" alt="curent-coverage" src="https://cloud.githubusercontent.com/assets/39992/15082642/e8ac42c8-1396-11e6-862c-d0bf60c22c12.png">

---

- [x] claim this issue (@mccullagh)
- [x] [Setup repository locally](https://github.com/hoodiehq/hoodie-client#testing) and make sure
      that all tests pass
- [x] Start a Pull Request #85
- [x] write tests until 100% coverage is reached. Check current coverage by running `npm run test:coverage`
- [ ] review & merge

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq) if you have ​​_any_​​ questions

**Comment by mccullagh** [comment]
I would like to try

**Comment by gr2m** [comment]
Thanks @mccullagh, it’s all yours :) I’ll be in the [Hoodie Chat](http://hood.ie/chat/) for the next 4h or so if you have any questions :)

**Comment by gr2m** [comment]
Thanks for the great work @mccullagh & welcome at Hoodie :) We’ve invited you to Hoodie Contributors team, you should see an invitation at https://github.com/hoodiehq. If you’d like to contribute again to one of Hoodie’s repositories, you can now create a branch instead of forking it, which makes collaboration more seamless.

I’d be great if you could star Hoodie’s main repository, so more people will find out about our work:
https://github.com/hoodiehq/hoodie :)

I’d be happy to help you find something else you can contribute to, just let me know if you are interested.
