### ISSUE TITLE
Implement hoodie.request(options)

### ISSUE THREAD

**Issue by gr2m** [hoodiehq/hoodie-client#9]
```js
hoodie.request(options)
```

Examples

```js
// sends a GET request to hoodie.url + '/foo/api/bar'
hoodie.request('/foo/api/bar')
// sends a GET request to another host
hoodie.request('https://example.com/foo/bar')
// sends a PATCH request to /foo/api/bar
hoodie.request({
  method: 'PATCH',
  url: '/foo/api/bar',
  data: {
    foo: 'bar'
  }
})
```

- [ ] Update [README.md](https://github.com/hoodiehq/hoodie-client/blob/master/README.md) as part of the PR

**Comment by gr2m** [comment]
https://github.com/hoodiehq/hoodie-client/blob/master/README.md

**Comment by gr2m** [comment]
@copasetickid is working on this one

**Comment by gr2m** [comment]
@copasetickid any update on this?

**Comment by copasetickid** [comment]
@gr2m  I haven't got a chance to work on this since the hoodie event that day. Feel free to reassign if necessary.

**Comment by gr2m** [comment]
Thanks for the update! So this ticket is available again :)

**Comment by andru** [comment]
I could pick this up.  

Ok to use the `nets` dependency as in `hoodie-client-account`?

**Comment by boennemann** [comment]
@andru That's awesome! Feel free to use modules, especially when they're used by other components already :)

**Comment by gr2m** [comment]
yeah we use `nets` on other modules, too
