### ISSUE TITLE
lodash as a module dependency (instead of devDependency)

### ISSUE THREAD

**Issue by brunopedroso** [hoodiehq/hoodie-client#96]
I've writen a script that requires `@hoodie/client`, just as described in the readme, but it throwed an error on require:

```
>> Error: Cannot find module 'lodash/defaultsDeep'
```

I suppose that's because my app's dependency tree ends up including an older version on lodash, and once `@hoodie/client` does not specify lodash as a dependency (only as a devDependency) it ends up using that older version, that does not have that file...

I tried to create a `node_modules` dir inside `node_mocules/@hoodie/client` and copy a newer version of lodash there and the error has gone.

Also, looking at the places where `defaultsDeep` is used in this module, it seems to me it's actually not only a dev dependency..

**Comment by gr2m** [comment]
yes, you are right, good catch! Could you please send a pull request to fix it? Commit the change with `fix(package): lodash ➞ dependencies`
